import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer";
import ScrollComponent from "@/components/ScrollComponent";
import localFont from "next/font/local";
import "../i18n";
import HandleLoadingComponent from "@/components/HandleLoadingComponent";

// open-sans font
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

// podcast font
const myFont = localFont({
  src: "./fonts/podcast/Podcast.ttf",
  variable: "--font-podcast",
});

export const metadata: Metadata = {
  title: "tours",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <head>
        <link rel="icon" href="/images/logo.webp" />
      </head>
      <body className={`antialiased ${myFont.variable}`}>
        <HandleLoadingComponent>
          <ScrollComponent />
          <NavBar />
          {children}
          <Footer />
        </HandleLoadingComponent>
      </body>
    </html>
  );
}
